Environment:
  case_path: "F:\\GIT\u6587\u4EF6\\mystudy\\\u5B66\u4E60\u8D44\u6599\\\u7F16\u7A0B\
    \u4E0E\u6D4B\u8BD5\\\u6D4B\u8BD5\u5DE5\u5177__Appium\\Project\\temp\\testsuite_tempdata\\\
    testsuite_debug/runningcase.xls"
  key1: aaa
  key2: sss
  key3: "F:\\GIT\u6587\u4EF6\\mystudy\\\u5B66\u4E60\u8D44\u6599\\\u7F16\u7A0B\u4E0E\
    \u6D4B\u8BD5\\\u6D4B\u8BD5\u5DE5\u5177__Appium\\Project"
  key5: "F:\\GIT\u6587\u4EF6\\mystudy\\\u5B66\u4E60\u8D44\u6599\\\u7F16\u7A0B\u4E0E\
    \u6D4B\u8BD5\\\u6D4B\u8BD5\u5DE5\u5177__Appium\\Project"
  row: 1
  sheet: 0
  testpath: .//
