'需要参数化的数据：
'userid：用户id
'ECIFID：ECIFID
'customername：客户姓名
'certid：证件号码
'repaymentaccount：还款账户
'repaymentaccountname：还款账户账户名
'accountbook：入账账户
'businesstype：业务品种
'businesssum：贷款总额
'term:期限
'employtype：雇佣类型

'需要获取的值全局值
'serialno：申请编号
'marketingprogram：营销方案
'paymentmethod：支付方式
'repaymentmethod：还款方式
'rapaymentcycle：

'初始化数据
'environment("userid")="008268"
'environment("customername")="刘九二"
'environment("certid")="350202199001010994"
'environment("repaymentaccount")="6231288300000328858"
'environment("repaymentaccountname")=environment("customername")
'environment("accountbook")=environment("repaymentaccount")
'environment("businesstype")="消费类标准工薪贷"
'environment("businesssum")="50000"
'environment("term")="12"
'environment("employtype")="标准受薪客户"
'environment("marketingprogram")="普通方案"
'environment("paymentmethod")="自主支付"
'environment("repaymentmethod")="等额本息"
'LoadFunctionLibrary PathFinder.Locate("..\..\QTP脚本集\函数库\CreditLibrary.qfl")

Environment.Value("UserID")="008268"'用户编号，必输，流程中重新赋值
Environment.Value("Serialno")=""'申请编号，非必输，流程中重新赋值
Environment.Value("ECIFID")=""'客户核心编号，非必输，流程中重新赋值
Environment.Value("CustomerName")="徐二"'客户姓名，必输
Environment.Value("CertID")="110100199101010024"'证件号码，必输
Environment.Value("EmployType")="标准受薪客户"'客户类型，必输
Environment.Value("BusinessSum")="200000.00"'贷款金额，必输
Environment.Value("Term")="24"'贷款期限，必输
Environment.Value("BusinessType")="消费类标准工薪贷"'贷款品种，必输
Environment.Value("MarketingProgram")="随心e贷专案放额度"'营销方案，必输
Environment.Value("Account")="6235957400006260666"'账号，必输
Environment.Value("CellphoneNumber")="16564720115"'手机号码，必输
Environment.Value("RepaymentType")="等额本息"'还款方式，必输
Environment.Value("已评分数据")=""