Environment:
  case_path: "F:/GIT\u6587\u4EF6/study/\u6D4B\u8BD5/\u63A5\u53E3\u6027\u80FD/\u6D4B\
    \u8BD5\u5DE5\u5177_Postman/PythonInterface/temp/runningdata/data_running/runningcase.xls"
  row: 1
  running_path: "F:/GIT\u6587\u4EF6/study/\u6D4B\u8BD5/\u63A5\u53E3\u6027\u80FD/\u6D4B\
    \u8BD5\u5DE5\u5177_Postman/PythonInterface/temp/runningdata/data_running"
  sheet_id: 0
