Environment:
  case_path: "F:/GIT\u6587\u4EF6/Study/\u6D4B\u8BD5/UI\u81EA\u52A8\u5316/Selenium/SeleniumPython/temp/runningdata/testcase-20190811230403-pid-16332/runningcase.xls"
  row: 2
  running_path: "F:/GIT\u6587\u4EF6/Study/\u6D4B\u8BD5/UI\u81EA\u52A8\u5316/Selenium/SeleniumPython/temp/runningdata/testcase-20190811230403-pid-16332"
  sheet_id: 0
